
USE ESCOLA;

CREATE TABLE ALUNO (
ALUCOD INT PRIMARY KEY,	
ALUMAT VARCHAR(50),
ALUNOME VARCHAR(100),
ALUDATACAD DATETIME,
ALUCPF VARCHAR(14),
ALUNOMEMAE VARCHAR(100),
ALUNOMEPAI VARCHAR(100),
ALUENDCEP VARCHAR(9),
ALUENDRUA VARCHAR(100),
ALUENDNUM VARCHAR(10),
ALUENDCOMP VARCHAR(30),
ALUENDBAIRRO VARCHAR(50),
ALUENDCIDADE VARCHAR(50)
);

SELECT ALUMAT, ALUNOME FROM ALUNO

SELECT * FROM ALUNO

UPDATE ALUNO
SET ALUNOME = 'ALUNO'

sp_help ALUNO
sp_who2
dbcc inputbuffer (145)

DROP TABLE ALUNO

--INSERT INTO ALUNO (ALUMAT, ALUNOME) VALUES (1, 'ALUNO 1') 
